require 'spec/rails/matchers/associations'

require 'rspec_validation_expectations/validation_expectations'
require 'rspec_validation_expectations/association_expectations'
require 'rspec_validation_expectations/other_expectations'